name: Maven Release and Build Workflow

on:
  push:
    branches:
      - main # Workflow uruchamia się na push do gałęzi main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Skonfiguruj JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Skonfiguruj dane użytkownika Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 4. Wymuś HTTPS jako zdalny adres
      - name: Ensure HTTPS remote
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${{ github.repository }}
          git remote -v

      # 5. Skonfiguruj Maven settings.xml
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      # 6. Wymuś HTTPS dla GIT (zamiana SSH na HTTPS)
      - name: Override GIT_SSH_COMMAND
        run: |
          git config core.sshCommand "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          git config --global url."https://github.com/".insteadOf ssh://git@github.com
          git remote set-url origin https://github.com/${{ github.repository }}
          git remote -v

      - name: Fetch all tags
        run: git fetch --tags


      - name: Clean Maven release state
      run: |
          rm -f release.properties

      # 7. Uruchom Maven Release Plugin
      - name: Maven Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn release:prepare release:perform -B -X

      # 8. Buduj projekt po release
      - name: Build Project
        run: mvn clean install

      # 9. Opcjonalnie: Przesyłanie artefaktu do GitHub Release
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/SortingApp.jar
          asset_name: SortingApp.jar
          asset_content_type: application/java-archive
