name: Maven Release and Build Workflow

on:
  push:
    branches:
      - main # Uruchamiaj na każdej aktualizacji głównej gałęzi

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Skonfiguruj JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Skonfiguruj dane użytkownika Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 4. Ustaw token GitHub (do tagowania i publikowania zmian)
      - name: Set up GitHub Token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${{ github.repository }}

      # 5. Uruchom Maven Release Plugin
      - name: Maven Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mvn release:prepare release:perform -B

      # 6. Buduj projekt po release
      - name: Build Project
        run: mvn clean install

      # 7. Opcjonalnie: Przesyłanie artefaktu do GitHub Release
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/SortingApp.jar
          asset_name: SortingApp.jar
          asset_content_type: application/java-archive
